/*
-- Query: SELECT * FROM my_project1.product
LIMIT 0, 1000

-- Date: 2018-11-13 15:50
*/
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007001,'中和汤',15.00,15.00,999,7,'myproduct/中和汤.jpg','中和汤是道地的安徽祁门传统名菜，\r\n属徽菜系，清澈味香，鲜嫩不腻，稀稠适中，老少皆宜。祁门人每逢\r\n置办酒席，都少不了中和汤，而且是上桌的第一道菜。中和原叫作“\r\n中河”。中河是发源于祁门流入江西鄱阳县境的一条河。');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007002,'红烧果子狸',56.00,56.00,999,7,'myproduct/红烧果子狸.jpg','红烧果子狸是安徽地区汉族传统\r\n名菜，属徽州菜系，咸甜味，狸肉酥烂醇香，色金红，汤汁稠亮，咸鲜\r\n口味中有甜味，十分可口。其中的辅料梨，不能与与螃蟹和鹅肉同食，\r\n否则会引起胃肠不适。该菜含有多种营养，如：蛋白质、脂肪、胡萝卜素和钙等。');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007003,'问政山笋',23.00,23.00,999,7,'myproduct/问政山笋.jpg','问政山笋是安徽地区的传统名菜，\r\n山笋鲜嫩，再加上香肠、香菇等，为这道菜增香不少，不仅颜色好看\r\n，而且味道也很好，受到很多人的喜爱。');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007004,'一品锅',15.99,15.99,888,7,'myproduct/一品锅.jpg','一品锅是徽州山区冬季常吃的汉族\r\n传统美食，属于火锅类。 相传，此菜由明代石台县“四部尚书”毕锵的\r\n一品诰命夫人余氏创制。一次，皇上突然驾临尚书府作客，席上出了山\r\n珍海味外，余夫人特意烧了一样徽州家常菜----火锅。不料皇上吃得津\r\n津有味，赞美不绝。后来，皇上得知美味的火锅竟是余夫人亲手所烧，\r\n便说原来还是“一品锅”！菜名就此一锤定了音。 “一品锅”的烹调比\r\n较讲究，在火锅里，锅底铺上干笋子，第二层铺上块肉，第三层是白豆\r\n腐或油炸豆腐，第四层是肉圆，第五层盖上粉丝，缀上菠菜或金针菜，\r\n加上调料和适量的水，然后用文火煨熟即成。');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007005,'徽州毛豆腐',15.00,15.00,999,7,'myproduct/徽州毛豆腐.jpg','毛豆腐也叫霉豆腐，徽州地区汉\r\n族传统名菜，是一种表面长有寸许白色茸毛的霉制品。主要做法是将\r\n豆腐切成块状，进行发酵的过程，使之长出寸许白毛，然后用油煎成\r\n两面略焦，再红烧。最有情趣的吃法是，在街头遇到走街串巷的货郎，\r\n一头挑干柴，一头挑毛豆腐，浇上香油，淋上辣椒糊，就着油锅边吃\r\n边聊，既鲜美可口，又独具风味。久居外地的徽州人，一说到毛豆腐，\r\n就会激起浓浓的思乡之情。');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007006,'火腿炖甲鱼',99.00,99.00,999,7,'myproduct/火腿炖甲鱼.png','甲鱼是一种营养丰富的食材,\r\n许多人都喜欢用它来煲汤,煲出来的汤不仅味道鲜美,而且非常滋补。\r\n火腿炖甲鱼是一道用甲鱼作为主要食材的滋补菜肴,也是徽菜中的经\r\n典名菜。冬天来一锅火腿炖甲鱼,整个人都会觉得暖洋洋的。');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007007,'凤炖牡丹',60.00,60.00,999,7,'myproduct/凤炖牡丹.png','凤炖牡丹是安徽省特色名菜，徽菜擅长烧、炖，作为传统炖菜典型\r\n代表之一。此菜系鸡与猪肚同锅，以小火细炖，汤色奶白浓厚，鸡\r\n酥鲜而含汁，肚质软烂而醇香。鸡肉的药用价值很大，民间有“济\r\n世良药”的美称。在徽州与沿江江南一带不仅作为筵席大菜，而且\r\n是产妇常食的滋补佳品。比较适合产妇、年老体弱及久病体虚者食用。');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007008,'徽州圆子',45.00,47.00,999,7,'myproduct/徽州圆子.png','“徽州圆子”是正宗徽菜品种\r\n之一。起源于歙县，别称“细沙炸肉”，约在200年前就己流传各地。\r\n');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007009,'黄山炖鸽',56.00,58.00,999,7,'myproduct/黄山炖鸽.png','黄山炖鸽是安徽黄山汉族传统名\r\n菜，取黄山菜鸽与黄山山药隔水炖制而成。汤清味鲜，鸽肉酥烂，\r\n山药清香爽口。此菜鸽肉滋味鲜美，营养丰富，易于消化，有补脑\r\n健肾、增强记忆力的食疗功效。山药肉松软细腻，略甜，富含淀粉，\r\n常被人们视作为滋补蔬菜食用。此菜又是一道滋补健身的佳肴。');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007010,'黄山臭鳜鱼',70.00,68.00,999,7,'myproduct/黄山臭鳜鱼.png','黄山臭鳜鱼又名腌鲜鳜鱼，是徽\r\n州地区汉族传统名菜，属于徽菜系。此菜烹制后以其香鲜透骨，鱼肉酥\r\n烂并带有特殊的芳香滋味而倍受广大食客的喜爱，许多来黄山旅游的客\r\n人都慕名前来品尝此肴，尝后都为有如此美味而赞不绝口。此菜历经200\r\n多年的历史，至今还具有如此影响力，关键在于它的特殊性，在烹制之\r\n前腌制后的鳜鱼闻起来“臭”，烹制后的鳜鱼吃起来香。这一“臭”一香\r\n，形成了鲜明的对比，更增加了此菜的魅力，使其成为徽菜的经典之一。');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007011,'清蒸石鸡',68.00,65.00,999,7,'myproduct/清蒸石鸡.png','清蒸石鸡是安徽黄山汉族传统名菜\r\n，此菜汤清香郁，肉细嫩柔滑，原味鲜醇，素以珍品著称。石鸡是栖息\r\n在山涧石缝中的一种蛙类动物，乃黄山特产。以休宁县大阜瀛所产最为\r\n著名。黄山石鸡每只重五两左右，腹乳白，背黑有条纹，肉质细嫩，含\r\n有丰富的蛋白质、钙等营养成分，并且具有清火、明目、滋补身体的功\r\n能，是山珍上品。');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007012,'当归獐肉',88.00,88.00,999,7,'myproduct/当归獐肉.png','当归獐肉，本品为徽州名菜，是皖\r\n南山区特有的传统美味。当归补血调经，活血止痛，润肠通埂；獐肉舒\r\n筋通络，健骨轻身。二者同煮，相得益彰。当归挥发出的芳香，能除去\r\n獐肉的异腥昧，再以雪里蕻提鲜，成为美不胜收的冬令佳肴。');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007013,'香菇盒',15.00,15.00,999,7,'myproduct/香菇盒.png','香菇盒是一道用香菇为原料做成\r\n的一道汉族家常菜。');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007014,'双爆串飞',23.00,22.00,999,7,'myproduct/双爆串飞.png','\"双爆串飞\",以山鸡和野鸭脯肉\r\n为主料,以青豆、鸡蛋清作佐料,用民间特有的方法制成。菜白绿相间,\r\n形如麻花,肉鲜嫩,略带葱、姜和花椒香味。');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007015,'香菇板栗',34.00,34.00,999,7,'myproduct/香菇板栗.png','香菇板栗是一道传统的汉族名菜，\r\n属于徽菜系。香菇的做法有很多，而香菇炒板栗是其中具有咸甜味风\r\n格的做法之一。把香菇切片，板栗用刀砍一下，刀入栗肉3/5，皮壳要\r\n相连，放入清水锅内烧开约1分钟，栗壳裂开时，趁热剥去外壳和内皮，\r\n栗肉用刀切成厚片。锅烧热放入豆油，将香菇、板栗片同时下锅煽炒，\r\n随即加入酱油、糖、姜末、鲜汤烧开后，改成小火焖3分钟，再改用旺\r\n火，加味精，用水淀粉勾芡，翻炒几下，淋入香油，即可装盘。\r\n');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007016,'杨梅丸子',15.00,15.00,999,7,'myproduct/杨梅丸子.png','杨梅丸子是一道传统特色菜肴，\r\n属于徽菜。 因形、色与杨梅相似，故名。肥瘦猪肉、马蹄、面包糠、\r\n鲜梅汁、糖、醋、盐等制作而成。');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007017,'双脆锅巴',15.00,15.00,999,7,'myproduct/双脆锅巴.png','双脆锅巴是一道传统的汉族名菜，\r\n属于徽菜。猪肚头及鸭肫,切花刀,放入香菇、笋、火腿片等汤中烧开。\r\n另将锅巴在油中炸黄,浇汤而成。酥香味美。');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007018,'蛏干烧肉',45.00,45.00,999,7,'myproduct/蛏干烧肉.png','蛏干烧肉是一道安徽徽州特色传统\r\n名菜。口味酱香味色泽酱红，质地酥烂，猪肉渗蛏鲜，蛏干增脂香。\r\n“蛏干”是竹蛏的干制品。肉味鲜香，含蛋白质很高，营养丰富。主\r\n要功效是产后恢复调理 滋阴调理 清热解毒调理。');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007019,'清蒸鹰龟',99.00,99.00,999,7,'myproduct/清蒸鹰龟.png','清蒸鹰龟是一道地方传统名菜，\r\n属于徽菜系，以鹰嘴龟、火腿、冰糖等为原料制成。龟与火腿共蒸，\r\n龟肉中的胶状物质溶入肠中，与火腿之香浓味相交融，使汤汁奶白\r\n而浓稠，龟肉鲜嫩且散发异香，是徽州山区珍品菜肴。具有防癌抗\r\n癌调理、滋阴调理、补血调理、止血调理等功效。');
INSERT INTO `product` (`pid`,`pname`,`estoreprice`,`markprice`,`pnum`,`cid`,`imgurl`,`desc`) VALUES (007020,'方腊鱼',68.00,68.00,999,7,'myproduct/方腊鱼.png','方腊鱼，是取鱼中上品鳜鱼，特别是皖南黄山一带山溪名产桃花鳜，采\r\n用多种烹调方法精制而成。此菜造型奇特，口味多样。鳜鱼在盘中昂首\r\n翘尾，有乘万顷波涛腾跃之势，是不可多得的黄山佳肴。方腊鱼又名“\r\n大鱼退兵将”。烹调方法有蒸的，有烧的、有炸的，有软熘的外加酿蟹\r\n盒的。其味咸鲜、香松、酸甜、滑嫩。一菜之中多形、多色、多味，可谓别有风味。');
